# Site settings
title: NYC Trees Count Data Jam
email: daniel.martin.sheehan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  NYC Trees Count Data Jam
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.nyctreescountdatajam.github.io" # the base hostname & protocol for your site
twitter_username: nygeog
github_username:  nygeog

# Build settings
markdown: kramdown
